struct K {
    static let restaurantLogSeg = "restaurantToHome"
    static let memberLogSeg = "memberToHome"
    static let cellNibName = "PostCell"
    static let cellIdentifier = "PostCell"
    static let MhomeToMCart = "MhomeToMCart"
    static let cartCell = "CartCell"
    static let CartToOrderConfirm = "CartToOrderConfirm"
    static let OrderConfirmToHome = "OrderConfirmToHome"
    
    struct FStore {

        static let restaurant = "restaurant"
        static let member = "member"
        static let name = "name"
        static let email = "email"
        static let street = "street"
        static let city = "city"
        static let state = "state"
        static let zip = "zip"
        static let phoneNumber = "phoneNumber"
        static let userType = "userType"
        static let memberName = "memberName"
        static let memberPhoneNum = "memberPhoneNum"
        static let memberEmail = "memberEmail"
        static let tags = "tags"
        static let description = "description"
        static let kitchenDays = "kitchenDays"
        
        static let orders = "orders"
        static let itemName = "name"
        static let unit = "unit"
        static let quantity = "quantity"
        static let price = "price"
        static let isAvail = "isAvail"
        static let avail = "avail"
        static let imagesFolder = "imagesFolder"
        static let imagesCollection = "imagesCollection"
        static let uid = "uid"
        static let imageUrl = "imageUrl"
        static let date = "date"
        static let resName = "resName"
        static let cart = "cart"
        static let memberOrders = "memberOrders"
        static let lastUpdated = "lastUpdated"
    }
}

